# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.3

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/heyizhu/Applications/Github/MinimalResolution-Spencer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/heyizhu/Applications/Github/MinimalResolution-Spencer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/heyizhu/Applications/Github/MinimalResolution-Spencer/CMakeFiles /Users/heyizhu/Applications/Github/MinimalResolution-Spencer//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/heyizhu/Applications/Github/MinimalResolution-Spencer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mr_st

# Build rule for target.
mr_st: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mr_st
.PHONY : mr_st

# fast build rule for target.
mr_st/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_st.dir/build.make CMakeFiles/mr_st.dir/build
.PHONY : mr_st/fast

#=============================================================================
# Target rules for targets named BPtab

# Build rule for target.
BPtab: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 BPtab
.PHONY : BPtab

# fast build rule for target.
BPtab/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BPtab.dir/build.make CMakeFiles/BPtab.dir/build
.PHONY : BPtab/fast

#=============================================================================
# Target rules for targets named mr_BP

# Build rule for target.
mr_BP: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mr_BP
.PHONY : mr_BP

# fast build rule for target.
mr_BP/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_BP.dir/build.make CMakeFiles/mr_BP.dir/build
.PHONY : mr_BP/fast

#=============================================================================
# Target rules for targets named mr_ex

# Build rule for target.
mr_ex: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mr_ex
.PHONY : mr_ex

# fast build rule for target.
mr_ex/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_ex.dir/build.make CMakeFiles/mr_ex.dir/build
.PHONY : mr_ex/fast

#=============================================================================
# Target rules for targets named mr_mot

# Build rule for target.
mr_mot: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mr_mot
.PHONY : mr_mot

# fast build rule for target.
mr_mot/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_mot.dir/build.make CMakeFiles/mr_mot.dir/build
.PHONY : mr_mot/fast

#=============================================================================
# Target rules for targets named mot_comb

# Build rule for target.
mot_comb: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mot_comb
.PHONY : mot_comb

# fast build rule for target.
mot_comb/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mot_comb.dir/build.make CMakeFiles/mot_comb.dir/build
.PHONY : mot_comb/fast

#=============================================================================
# Target rules for targets named motTab

# Build rule for target.
motTab: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 motTab
.PHONY : motTab

# fast build rule for target.
motTab/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/motTab.dir/build.make CMakeFiles/motTab.dir/build
.PHONY : motTab/fast

#=============================================================================
# Target rules for targets named kos

# Build rule for target.
kos: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 kos
.PHONY : kos

# fast build rule for target.
kos/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kos.dir/build.make CMakeFiles/kos.dir/build
.PHONY : kos/fast

#=============================================================================
# Target rules for targets named mot_mult

# Build rule for target.
mot_mult: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mot_mult
.PHONY : mot_mult

# fast build rule for target.
mot_mult/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mot_mult.dir/build.make CMakeFiles/mot_mult.dir/build
.PHONY : mot_mult/fast

#=============================================================================
# Target rules for targets named yoneda

# Build rule for target.
yoneda: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 yoneda
.PHONY : yoneda

# fast build rule for target.
yoneda/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yoneda.dir/build.make CMakeFiles/yoneda.dir/build
.PHONY : yoneda/fast

#=============================================================================
# Target rules for targets named tauBoc

# Build rule for target.
tauBoc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tauBoc
.PHONY : tauBoc

# fast build rule for target.
tauBoc/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tauBoc.dir/build.make CMakeFiles/tauBoc.dir/build
.PHONY : tauBoc/fast

#=============================================================================
# Target rules for targets named e2p

# Build rule for target.
e2p: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 e2p
.PHONY : e2p

# fast build rule for target.
e2p/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/e2p.dir/build.make CMakeFiles/e2p.dir/build
.PHONY : e2p/fast

BP.o: BP.cpp.o
.PHONY : BP.o

# target to build an object file
BP.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BPtab.dir/build.make CMakeFiles/BPtab.dir/BP.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_BP.dir/build.make CMakeFiles/mr_BP.dir/BP.cpp.o
.PHONY : BP.cpp.o

BP.i: BP.cpp.i
.PHONY : BP.i

# target to preprocess a source file
BP.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BPtab.dir/build.make CMakeFiles/BPtab.dir/BP.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_BP.dir/build.make CMakeFiles/mr_BP.dir/BP.cpp.i
.PHONY : BP.cpp.i

BP.s: BP.cpp.s
.PHONY : BP.s

# target to generate assembly for a file
BP.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BPtab.dir/build.make CMakeFiles/BPtab.dir/BP.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_BP.dir/build.make CMakeFiles/mr_BP.dir/BP.cpp.s
.PHONY : BP.cpp.s

BPQ.o: BPQ.cpp.o
.PHONY : BPQ.o

# target to build an object file
BPQ.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BPtab.dir/build.make CMakeFiles/BPtab.dir/BPQ.cpp.o
.PHONY : BPQ.cpp.o

BPQ.i: BPQ.cpp.i
.PHONY : BPQ.i

# target to preprocess a source file
BPQ.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BPtab.dir/build.make CMakeFiles/BPtab.dir/BPQ.cpp.i
.PHONY : BPQ.cpp.i

BPQ.s: BPQ.cpp.s
.PHONY : BPQ.s

# target to generate assembly for a file
BPQ.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BPtab.dir/build.make CMakeFiles/BPtab.dir/BPQ.cpp.s
.PHONY : BPQ.cpp.s

BP_init.o: BP_init.cpp.o
.PHONY : BP_init.o

# target to build an object file
BP_init.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_BP.dir/build.make CMakeFiles/mr_BP.dir/BP_init.cpp.o
.PHONY : BP_init.cpp.o

BP_init.i: BP_init.cpp.i
.PHONY : BP_init.i

# target to preprocess a source file
BP_init.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_BP.dir/build.make CMakeFiles/mr_BP.dir/BP_init.cpp.i
.PHONY : BP_init.cpp.i

BP_init.s: BP_init.cpp.s
.PHONY : BP_init.s

# target to generate assembly for a file
BP_init.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_BP.dir/build.make CMakeFiles/mr_BP.dir/BP_init.cpp.s
.PHONY : BP_init.cpp.s

BPcomplex.o: BPcomplex.cpp.o
.PHONY : BPcomplex.o

# target to build an object file
BPcomplex.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_BP.dir/build.make CMakeFiles/mr_BP.dir/BPcomplex.cpp.o
.PHONY : BPcomplex.cpp.o

BPcomplex.i: BPcomplex.cpp.i
.PHONY : BPcomplex.i

# target to preprocess a source file
BPcomplex.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_BP.dir/build.make CMakeFiles/mr_BP.dir/BPcomplex.cpp.i
.PHONY : BPcomplex.cpp.i

BPcomplex.s: BPcomplex.cpp.s
.PHONY : BPcomplex.s

# target to generate assembly for a file
BPcomplex.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_BP.dir/build.make CMakeFiles/mr_BP.dir/BPcomplex.cpp.s
.PHONY : BPcomplex.cpp.s

BPmain.o: BPmain.cpp.o
.PHONY : BPmain.o

# target to build an object file
BPmain.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_BP.dir/build.make CMakeFiles/mr_BP.dir/BPmain.cpp.o
.PHONY : BPmain.cpp.o

BPmain.i: BPmain.cpp.i
.PHONY : BPmain.i

# target to preprocess a source file
BPmain.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_BP.dir/build.make CMakeFiles/mr_BP.dir/BPmain.cpp.i
.PHONY : BPmain.cpp.i

BPmain.s: BPmain.cpp.s
.PHONY : BPmain.s

# target to generate assembly for a file
BPmain.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_BP.dir/build.make CMakeFiles/mr_BP.dir/BPmain.cpp.s
.PHONY : BPmain.cpp.s

BPtable.o: BPtable.cpp.o
.PHONY : BPtable.o

# target to build an object file
BPtable.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BPtab.dir/build.make CMakeFiles/BPtab.dir/BPtable.cpp.o
.PHONY : BPtable.cpp.o

BPtable.i: BPtable.cpp.i
.PHONY : BPtable.i

# target to preprocess a source file
BPtable.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BPtab.dir/build.make CMakeFiles/BPtab.dir/BPtable.cpp.i
.PHONY : BPtable.cpp.i

BPtable.s: BPtable.cpp.s
.PHONY : BPtable.s

# target to generate assembly for a file
BPtable.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BPtab.dir/build.make CMakeFiles/BPtab.dir/BPtable.cpp.s
.PHONY : BPtable.cpp.s

Boc.o: Boc.cpp.o
.PHONY : Boc.o

# target to build an object file
Boc.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_BP.dir/build.make CMakeFiles/mr_BP.dir/Boc.cpp.o
.PHONY : Boc.cpp.o

Boc.i: Boc.cpp.i
.PHONY : Boc.i

# target to preprocess a source file
Boc.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_BP.dir/build.make CMakeFiles/mr_BP.dir/Boc.cpp.i
.PHONY : Boc.cpp.i

Boc.s: Boc.cpp.s
.PHONY : Boc.s

# target to generate assembly for a file
Boc.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_BP.dir/build.make CMakeFiles/mr_BP.dir/Boc.cpp.s
.PHONY : Boc.cpp.s

Fp.o: Fp.cpp.o
.PHONY : Fp.o

# target to build an object file
Fp.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_st.dir/build.make CMakeFiles/mr_st.dir/Fp.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BPtab.dir/build.make CMakeFiles/BPtab.dir/Fp.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_BP.dir/build.make CMakeFiles/mr_BP.dir/Fp.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_ex.dir/build.make CMakeFiles/mr_ex.dir/Fp.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_mot.dir/build.make CMakeFiles/mr_mot.dir/Fp.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mot_comb.dir/build.make CMakeFiles/mot_comb.dir/Fp.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kos.dir/build.make CMakeFiles/kos.dir/Fp.cpp.o
.PHONY : Fp.cpp.o

Fp.i: Fp.cpp.i
.PHONY : Fp.i

# target to preprocess a source file
Fp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_st.dir/build.make CMakeFiles/mr_st.dir/Fp.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BPtab.dir/build.make CMakeFiles/BPtab.dir/Fp.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_BP.dir/build.make CMakeFiles/mr_BP.dir/Fp.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_ex.dir/build.make CMakeFiles/mr_ex.dir/Fp.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_mot.dir/build.make CMakeFiles/mr_mot.dir/Fp.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mot_comb.dir/build.make CMakeFiles/mot_comb.dir/Fp.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kos.dir/build.make CMakeFiles/kos.dir/Fp.cpp.i
.PHONY : Fp.cpp.i

Fp.s: Fp.cpp.s
.PHONY : Fp.s

# target to generate assembly for a file
Fp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_st.dir/build.make CMakeFiles/mr_st.dir/Fp.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BPtab.dir/build.make CMakeFiles/BPtab.dir/Fp.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_BP.dir/build.make CMakeFiles/mr_BP.dir/Fp.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_ex.dir/build.make CMakeFiles/mr_ex.dir/Fp.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_mot.dir/build.make CMakeFiles/mr_mot.dir/Fp.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mot_comb.dir/build.make CMakeFiles/mot_comb.dir/Fp.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kos.dir/build.make CMakeFiles/kos.dir/Fp.cpp.s
.PHONY : Fp.cpp.s

Qp.o: Qp.cpp.o
.PHONY : Qp.o

# target to build an object file
Qp.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BPtab.dir/build.make CMakeFiles/BPtab.dir/Qp.cpp.o
.PHONY : Qp.cpp.o

Qp.i: Qp.cpp.i
.PHONY : Qp.i

# target to preprocess a source file
Qp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BPtab.dir/build.make CMakeFiles/BPtab.dir/Qp.cpp.i
.PHONY : Qp.cpp.i

Qp.s: Qp.cpp.s
.PHONY : Qp.s

# target to generate assembly for a file
Qp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BPtab.dir/build.make CMakeFiles/BPtab.dir/Qp.cpp.s
.PHONY : Qp.cpp.s

Z2.o: Z2.cpp.o
.PHONY : Z2.o

# target to build an object file
Z2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BPtab.dir/build.make CMakeFiles/BPtab.dir/Z2.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_BP.dir/build.make CMakeFiles/mr_BP.dir/Z2.cpp.o
.PHONY : Z2.cpp.o

Z2.i: Z2.cpp.i
.PHONY : Z2.i

# target to preprocess a source file
Z2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BPtab.dir/build.make CMakeFiles/BPtab.dir/Z2.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_BP.dir/build.make CMakeFiles/mr_BP.dir/Z2.cpp.i
.PHONY : Z2.cpp.i

Z2.s: Z2.cpp.s
.PHONY : Z2.s

# target to generate assembly for a file
Z2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BPtab.dir/build.make CMakeFiles/BPtab.dir/Z2.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_BP.dir/build.make CMakeFiles/mr_BP.dir/Z2.cpp.s
.PHONY : Z2.cpp.s

algNov.o: algNov.cpp.o
.PHONY : algNov.o

# target to build an object file
algNov.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_BP.dir/build.make CMakeFiles/mr_BP.dir/algNov.cpp.o
.PHONY : algNov.cpp.o

algNov.i: algNov.cpp.i
.PHONY : algNov.i

# target to preprocess a source file
algNov.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_BP.dir/build.make CMakeFiles/mr_BP.dir/algNov.cpp.i
.PHONY : algNov.cpp.i

algNov.s: algNov.cpp.s
.PHONY : algNov.s

# target to generate assembly for a file
algNov.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_BP.dir/build.make CMakeFiles/mr_BP.dir/algNov.cpp.s
.PHONY : algNov.cpp.s

ctau_steenrod.o: ctau_steenrod.cpp.o
.PHONY : ctau_steenrod.o

# target to build an object file
ctau_steenrod.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_ex.dir/build.make CMakeFiles/mr_ex.dir/ctau_steenrod.cpp.o
.PHONY : ctau_steenrod.cpp.o

ctau_steenrod.i: ctau_steenrod.cpp.i
.PHONY : ctau_steenrod.i

# target to preprocess a source file
ctau_steenrod.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_ex.dir/build.make CMakeFiles/mr_ex.dir/ctau_steenrod.cpp.i
.PHONY : ctau_steenrod.cpp.i

ctau_steenrod.s: ctau_steenrod.cpp.s
.PHONY : ctau_steenrod.s

# target to generate assembly for a file
ctau_steenrod.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_ex.dir/build.make CMakeFiles/mr_ex.dir/ctau_steenrod.cpp.s
.PHONY : ctau_steenrod.cpp.s

ex2poly.o: ex2poly.cpp.o
.PHONY : ex2poly.o

# target to build an object file
ex2poly.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/e2p.dir/build.make CMakeFiles/e2p.dir/ex2poly.cpp.o
.PHONY : ex2poly.cpp.o

ex2poly.i: ex2poly.cpp.i
.PHONY : ex2poly.i

# target to preprocess a source file
ex2poly.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/e2p.dir/build.make CMakeFiles/e2p.dir/ex2poly.cpp.i
.PHONY : ex2poly.cpp.i

ex2poly.s: ex2poly.cpp.s
.PHONY : ex2poly.s

# target to generate assembly for a file
ex2poly.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/e2p.dir/build.make CMakeFiles/e2p.dir/ex2poly.cpp.s
.PHONY : ex2poly.cpp.s

ex_exponents.o: ex_exponents.cpp.o
.PHONY : ex_exponents.o

# target to build an object file
ex_exponents.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_ex.dir/build.make CMakeFiles/mr_ex.dir/ex_exponents.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/e2p.dir/build.make CMakeFiles/e2p.dir/ex_exponents.cpp.o
.PHONY : ex_exponents.cpp.o

ex_exponents.i: ex_exponents.cpp.i
.PHONY : ex_exponents.i

# target to preprocess a source file
ex_exponents.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_ex.dir/build.make CMakeFiles/mr_ex.dir/ex_exponents.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/e2p.dir/build.make CMakeFiles/e2p.dir/ex_exponents.cpp.i
.PHONY : ex_exponents.cpp.i

ex_exponents.s: ex_exponents.cpp.s
.PHONY : ex_exponents.s

# target to generate assembly for a file
ex_exponents.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_ex.dir/build.make CMakeFiles/mr_ex.dir/ex_exponents.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/e2p.dir/build.make CMakeFiles/e2p.dir/ex_exponents.cpp.s
.PHONY : ex_exponents.cpp.s

ex_index.o: ex_index.cpp.o
.PHONY : ex_index.o

# target to build an object file
ex_index.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_ex.dir/build.make CMakeFiles/mr_ex.dir/ex_index.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/e2p.dir/build.make CMakeFiles/e2p.dir/ex_index.cpp.o
.PHONY : ex_index.cpp.o

ex_index.i: ex_index.cpp.i
.PHONY : ex_index.i

# target to preprocess a source file
ex_index.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_ex.dir/build.make CMakeFiles/mr_ex.dir/ex_index.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/e2p.dir/build.make CMakeFiles/e2p.dir/ex_index.cpp.i
.PHONY : ex_index.cpp.i

ex_index.s: ex_index.cpp.s
.PHONY : ex_index.s

# target to generate assembly for a file
ex_index.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_ex.dir/build.make CMakeFiles/mr_ex.dir/ex_index.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/e2p.dir/build.make CMakeFiles/e2p.dir/ex_index.cpp.s
.PHONY : ex_index.cpp.s

ex_main.o: ex_main.cpp.o
.PHONY : ex_main.o

# target to build an object file
ex_main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_ex.dir/build.make CMakeFiles/mr_ex.dir/ex_main.cpp.o
.PHONY : ex_main.cpp.o

ex_main.i: ex_main.cpp.i
.PHONY : ex_main.i

# target to preprocess a source file
ex_main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_ex.dir/build.make CMakeFiles/mr_ex.dir/ex_main.cpp.i
.PHONY : ex_main.cpp.i

ex_main.s: ex_main.cpp.s
.PHONY : ex_main.s

# target to generate assembly for a file
ex_main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_ex.dir/build.make CMakeFiles/mr_ex.dir/ex_main.cpp.s
.PHONY : ex_main.cpp.s

ex_steenrod_init.o: ex_steenrod_init.cpp.o
.PHONY : ex_steenrod_init.o

# target to build an object file
ex_steenrod_init.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_ex.dir/build.make CMakeFiles/mr_ex.dir/ex_steenrod_init.cpp.o
.PHONY : ex_steenrod_init.cpp.o

ex_steenrod_init.i: ex_steenrod_init.cpp.i
.PHONY : ex_steenrod_init.i

# target to preprocess a source file
ex_steenrod_init.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_ex.dir/build.make CMakeFiles/mr_ex.dir/ex_steenrod_init.cpp.i
.PHONY : ex_steenrod_init.cpp.i

ex_steenrod_init.s: ex_steenrod_init.cpp.s
.PHONY : ex_steenrod_init.s

# target to generate assembly for a file
ex_steenrod_init.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_ex.dir/build.make CMakeFiles/mr_ex.dir/ex_steenrod_init.cpp.s
.PHONY : ex_steenrod_init.cpp.s

exponents.o: exponents.cpp.o
.PHONY : exponents.o

# target to build an object file
exponents.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_st.dir/build.make CMakeFiles/mr_st.dir/exponents.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BPtab.dir/build.make CMakeFiles/BPtab.dir/exponents.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_BP.dir/build.make CMakeFiles/mr_BP.dir/exponents.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_mot.dir/build.make CMakeFiles/mr_mot.dir/exponents.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mot_comb.dir/build.make CMakeFiles/mot_comb.dir/exponents.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/motTab.dir/build.make CMakeFiles/motTab.dir/exponents.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kos.dir/build.make CMakeFiles/kos.dir/exponents.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mot_mult.dir/build.make CMakeFiles/mot_mult.dir/exponents.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yoneda.dir/build.make CMakeFiles/yoneda.dir/exponents.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tauBoc.dir/build.make CMakeFiles/tauBoc.dir/exponents.cpp.o
.PHONY : exponents.cpp.o

exponents.i: exponents.cpp.i
.PHONY : exponents.i

# target to preprocess a source file
exponents.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_st.dir/build.make CMakeFiles/mr_st.dir/exponents.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BPtab.dir/build.make CMakeFiles/BPtab.dir/exponents.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_BP.dir/build.make CMakeFiles/mr_BP.dir/exponents.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_mot.dir/build.make CMakeFiles/mr_mot.dir/exponents.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mot_comb.dir/build.make CMakeFiles/mot_comb.dir/exponents.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/motTab.dir/build.make CMakeFiles/motTab.dir/exponents.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kos.dir/build.make CMakeFiles/kos.dir/exponents.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mot_mult.dir/build.make CMakeFiles/mot_mult.dir/exponents.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yoneda.dir/build.make CMakeFiles/yoneda.dir/exponents.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tauBoc.dir/build.make CMakeFiles/tauBoc.dir/exponents.cpp.i
.PHONY : exponents.cpp.i

exponents.s: exponents.cpp.s
.PHONY : exponents.s

# target to generate assembly for a file
exponents.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_st.dir/build.make CMakeFiles/mr_st.dir/exponents.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BPtab.dir/build.make CMakeFiles/BPtab.dir/exponents.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_BP.dir/build.make CMakeFiles/mr_BP.dir/exponents.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_mot.dir/build.make CMakeFiles/mr_mot.dir/exponents.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mot_comb.dir/build.make CMakeFiles/mot_comb.dir/exponents.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/motTab.dir/build.make CMakeFiles/motTab.dir/exponents.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kos.dir/build.make CMakeFiles/kos.dir/exponents.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mot_mult.dir/build.make CMakeFiles/mot_mult.dir/exponents.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yoneda.dir/build.make CMakeFiles/yoneda.dir/exponents.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tauBoc.dir/build.make CMakeFiles/tauBoc.dir/exponents.cpp.s
.PHONY : exponents.cpp.s

kosul.o: kosul.cpp.o
.PHONY : kosul.o

# target to build an object file
kosul.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kos.dir/build.make CMakeFiles/kos.dir/kosul.cpp.o
.PHONY : kosul.cpp.o

kosul.i: kosul.cpp.i
.PHONY : kosul.i

# target to preprocess a source file
kosul.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kos.dir/build.make CMakeFiles/kos.dir/kosul.cpp.i
.PHONY : kosul.cpp.i

kosul.s: kosul.cpp.s
.PHONY : kosul.s

# target to generate assembly for a file
kosul.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kos.dir/build.make CMakeFiles/kos.dir/kosul.cpp.s
.PHONY : kosul.cpp.s

mon_index.o: mon_index.cpp.o
.PHONY : mon_index.o

# target to build an object file
mon_index.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_st.dir/build.make CMakeFiles/mr_st.dir/mon_index.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BPtab.dir/build.make CMakeFiles/BPtab.dir/mon_index.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_BP.dir/build.make CMakeFiles/mr_BP.dir/mon_index.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/motTab.dir/build.make CMakeFiles/motTab.dir/mon_index.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kos.dir/build.make CMakeFiles/kos.dir/mon_index.cpp.o
.PHONY : mon_index.cpp.o

mon_index.i: mon_index.cpp.i
.PHONY : mon_index.i

# target to preprocess a source file
mon_index.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_st.dir/build.make CMakeFiles/mr_st.dir/mon_index.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BPtab.dir/build.make CMakeFiles/BPtab.dir/mon_index.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_BP.dir/build.make CMakeFiles/mr_BP.dir/mon_index.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/motTab.dir/build.make CMakeFiles/motTab.dir/mon_index.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kos.dir/build.make CMakeFiles/kos.dir/mon_index.cpp.i
.PHONY : mon_index.cpp.i

mon_index.s: mon_index.cpp.s
.PHONY : mon_index.s

# target to generate assembly for a file
mon_index.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_st.dir/build.make CMakeFiles/mr_st.dir/mon_index.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BPtab.dir/build.make CMakeFiles/BPtab.dir/mon_index.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_BP.dir/build.make CMakeFiles/mr_BP.dir/mon_index.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/motTab.dir/build.make CMakeFiles/motTab.dir/mon_index.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kos.dir/build.make CMakeFiles/kos.dir/mon_index.cpp.s
.PHONY : mon_index.cpp.s

mot_coactions.o: mot_coactions.cpp.o
.PHONY : mot_coactions.o

# target to build an object file
mot_coactions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/motTab.dir/build.make CMakeFiles/motTab.dir/mot_coactions.cpp.o
.PHONY : mot_coactions.cpp.o

mot_coactions.i: mot_coactions.cpp.i
.PHONY : mot_coactions.i

# target to preprocess a source file
mot_coactions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/motTab.dir/build.make CMakeFiles/motTab.dir/mot_coactions.cpp.i
.PHONY : mot_coactions.cpp.i

mot_coactions.s: mot_coactions.cpp.s
.PHONY : mot_coactions.s

# target to generate assembly for a file
mot_coactions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/motTab.dir/build.make CMakeFiles/motTab.dir/mot_coactions.cpp.s
.PHONY : mot_coactions.cpp.s

mot_combine.o: mot_combine.cpp.o
.PHONY : mot_combine.o

# target to build an object file
mot_combine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mot_comb.dir/build.make CMakeFiles/mot_comb.dir/mot_combine.cpp.o
.PHONY : mot_combine.cpp.o

mot_combine.i: mot_combine.cpp.i
.PHONY : mot_combine.i

# target to preprocess a source file
mot_combine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mot_comb.dir/build.make CMakeFiles/mot_comb.dir/mot_combine.cpp.i
.PHONY : mot_combine.cpp.i

mot_combine.s: mot_combine.cpp.s
.PHONY : mot_combine.s

# target to generate assembly for a file
mot_combine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mot_comb.dir/build.make CMakeFiles/mot_comb.dir/mot_combine.cpp.s
.PHONY : mot_combine.cpp.s

mot_main.o: mot_main.cpp.o
.PHONY : mot_main.o

# target to build an object file
mot_main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_mot.dir/build.make CMakeFiles/mr_mot.dir/mot_main.cpp.o
.PHONY : mot_main.cpp.o

mot_main.i: mot_main.cpp.i
.PHONY : mot_main.i

# target to preprocess a source file
mot_main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_mot.dir/build.make CMakeFiles/mr_mot.dir/mot_main.cpp.i
.PHONY : mot_main.cpp.i

mot_main.s: mot_main.cpp.s
.PHONY : mot_main.s

# target to generate assembly for a file
mot_main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_mot.dir/build.make CMakeFiles/mr_mot.dir/mot_main.cpp.s
.PHONY : mot_main.cpp.s

mot_mult.o: mot_mult.cpp.o
.PHONY : mot_mult.o

# target to build an object file
mot_mult.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mot_mult.dir/build.make CMakeFiles/mot_mult.dir/mot_mult.cpp.o
.PHONY : mot_mult.cpp.o

mot_mult.i: mot_mult.cpp.i
.PHONY : mot_mult.i

# target to preprocess a source file
mot_mult.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mot_mult.dir/build.make CMakeFiles/mot_mult.dir/mot_mult.cpp.i
.PHONY : mot_mult.cpp.i

mot_mult.s: mot_mult.cpp.s
.PHONY : mot_mult.s

# target to generate assembly for a file
mot_mult.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mot_mult.dir/build.make CMakeFiles/mot_mult.dir/mot_mult.cpp.s
.PHONY : mot_mult.cpp.s

mot_steenrod.o: mot_steenrod.cpp.o
.PHONY : mot_steenrod.o

# target to build an object file
mot_steenrod.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_mot.dir/build.make CMakeFiles/mr_mot.dir/mot_steenrod.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mot_comb.dir/build.make CMakeFiles/mot_comb.dir/mot_steenrod.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/motTab.dir/build.make CMakeFiles/motTab.dir/mot_steenrod.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mot_mult.dir/build.make CMakeFiles/mot_mult.dir/mot_steenrod.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yoneda.dir/build.make CMakeFiles/yoneda.dir/mot_steenrod.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tauBoc.dir/build.make CMakeFiles/tauBoc.dir/mot_steenrod.cpp.o
.PHONY : mot_steenrod.cpp.o

mot_steenrod.i: mot_steenrod.cpp.i
.PHONY : mot_steenrod.i

# target to preprocess a source file
mot_steenrod.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_mot.dir/build.make CMakeFiles/mr_mot.dir/mot_steenrod.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mot_comb.dir/build.make CMakeFiles/mot_comb.dir/mot_steenrod.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/motTab.dir/build.make CMakeFiles/motTab.dir/mot_steenrod.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mot_mult.dir/build.make CMakeFiles/mot_mult.dir/mot_steenrod.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yoneda.dir/build.make CMakeFiles/yoneda.dir/mot_steenrod.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tauBoc.dir/build.make CMakeFiles/tauBoc.dir/mot_steenrod.cpp.i
.PHONY : mot_steenrod.cpp.i

mot_steenrod.s: mot_steenrod.cpp.s
.PHONY : mot_steenrod.s

# target to generate assembly for a file
mot_steenrod.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_mot.dir/build.make CMakeFiles/mr_mot.dir/mot_steenrod.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mot_comb.dir/build.make CMakeFiles/mot_comb.dir/mot_steenrod.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/motTab.dir/build.make CMakeFiles/motTab.dir/mot_steenrod.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mot_mult.dir/build.make CMakeFiles/mot_mult.dir/mot_steenrod.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yoneda.dir/build.make CMakeFiles/yoneda.dir/mot_steenrod.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tauBoc.dir/build.make CMakeFiles/tauBoc.dir/mot_steenrod.cpp.s
.PHONY : mot_steenrod.cpp.s

multiplication.o: multiplication.cpp.o
.PHONY : multiplication.o

# target to build an object file
multiplication.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_BP.dir/build.make CMakeFiles/mr_BP.dir/multiplication.cpp.o
.PHONY : multiplication.cpp.o

multiplication.i: multiplication.cpp.i
.PHONY : multiplication.i

# target to preprocess a source file
multiplication.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_BP.dir/build.make CMakeFiles/mr_BP.dir/multiplication.cpp.i
.PHONY : multiplication.cpp.i

multiplication.s: multiplication.cpp.s
.PHONY : multiplication.s

# target to generate assembly for a file
multiplication.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_BP.dir/build.make CMakeFiles/mr_BP.dir/multiplication.cpp.s
.PHONY : multiplication.cpp.s

steenrod.o: steenrod.cpp.o
.PHONY : steenrod.o

# target to build an object file
steenrod.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_st.dir/build.make CMakeFiles/mr_st.dir/steenrod.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kos.dir/build.make CMakeFiles/kos.dir/steenrod.cpp.o
.PHONY : steenrod.cpp.o

steenrod.i: steenrod.cpp.i
.PHONY : steenrod.i

# target to preprocess a source file
steenrod.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_st.dir/build.make CMakeFiles/mr_st.dir/steenrod.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kos.dir/build.make CMakeFiles/kos.dir/steenrod.cpp.i
.PHONY : steenrod.cpp.i

steenrod.s: steenrod.cpp.s
.PHONY : steenrod.s

# target to generate assembly for a file
steenrod.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_st.dir/build.make CMakeFiles/mr_st.dir/steenrod.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kos.dir/build.make CMakeFiles/kos.dir/steenrod.cpp.s
.PHONY : steenrod.cpp.s

steenrod_init.o: steenrod_init.cpp.o
.PHONY : steenrod_init.o

# target to build an object file
steenrod_init.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_st.dir/build.make CMakeFiles/mr_st.dir/steenrod_init.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kos.dir/build.make CMakeFiles/kos.dir/steenrod_init.cpp.o
.PHONY : steenrod_init.cpp.o

steenrod_init.i: steenrod_init.cpp.i
.PHONY : steenrod_init.i

# target to preprocess a source file
steenrod_init.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_st.dir/build.make CMakeFiles/mr_st.dir/steenrod_init.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kos.dir/build.make CMakeFiles/kos.dir/steenrod_init.cpp.i
.PHONY : steenrod_init.cpp.i

steenrod_init.s: steenrod_init.cpp.s
.PHONY : steenrod_init.s

# target to generate assembly for a file
steenrod_init.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_st.dir/build.make CMakeFiles/mr_st.dir/steenrod_init.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kos.dir/build.make CMakeFiles/kos.dir/steenrod_init.cpp.s
.PHONY : steenrod_init.cpp.s

stmain.o: stmain.cpp.o
.PHONY : stmain.o

# target to build an object file
stmain.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_st.dir/build.make CMakeFiles/mr_st.dir/stmain.cpp.o
.PHONY : stmain.cpp.o

stmain.i: stmain.cpp.i
.PHONY : stmain.i

# target to preprocess a source file
stmain.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_st.dir/build.make CMakeFiles/mr_st.dir/stmain.cpp.i
.PHONY : stmain.cpp.i

stmain.s: stmain.cpp.s
.PHONY : stmain.s

# target to generate assembly for a file
stmain.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_st.dir/build.make CMakeFiles/mr_st.dir/stmain.cpp.s
.PHONY : stmain.cpp.s

streams.o: streams.cpp.o
.PHONY : streams.o

# target to build an object file
streams.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_BP.dir/build.make CMakeFiles/mr_BP.dir/streams.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_ex.dir/build.make CMakeFiles/mr_ex.dir/streams.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_mot.dir/build.make CMakeFiles/mr_mot.dir/streams.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mot_comb.dir/build.make CMakeFiles/mot_comb.dir/streams.cpp.o
.PHONY : streams.cpp.o

streams.i: streams.cpp.i
.PHONY : streams.i

# target to preprocess a source file
streams.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_BP.dir/build.make CMakeFiles/mr_BP.dir/streams.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_ex.dir/build.make CMakeFiles/mr_ex.dir/streams.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_mot.dir/build.make CMakeFiles/mr_mot.dir/streams.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mot_comb.dir/build.make CMakeFiles/mot_comb.dir/streams.cpp.i
.PHONY : streams.cpp.i

streams.s: streams.cpp.s
.PHONY : streams.s

# target to generate assembly for a file
streams.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_BP.dir/build.make CMakeFiles/mr_BP.dir/streams.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_ex.dir/build.make CMakeFiles/mr_ex.dir/streams.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mr_mot.dir/build.make CMakeFiles/mr_mot.dir/streams.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mot_comb.dir/build.make CMakeFiles/mot_comb.dir/streams.cpp.s
.PHONY : streams.cpp.s

tao_bockstein.o: tao_bockstein.cpp.o
.PHONY : tao_bockstein.o

# target to build an object file
tao_bockstein.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mot_mult.dir/build.make CMakeFiles/mot_mult.dir/tao_bockstein.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yoneda.dir/build.make CMakeFiles/yoneda.dir/tao_bockstein.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tauBoc.dir/build.make CMakeFiles/tauBoc.dir/tao_bockstein.cpp.o
.PHONY : tao_bockstein.cpp.o

tao_bockstein.i: tao_bockstein.cpp.i
.PHONY : tao_bockstein.i

# target to preprocess a source file
tao_bockstein.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mot_mult.dir/build.make CMakeFiles/mot_mult.dir/tao_bockstein.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yoneda.dir/build.make CMakeFiles/yoneda.dir/tao_bockstein.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tauBoc.dir/build.make CMakeFiles/tauBoc.dir/tao_bockstein.cpp.i
.PHONY : tao_bockstein.cpp.i

tao_bockstein.s: tao_bockstein.cpp.s
.PHONY : tao_bockstein.s

# target to generate assembly for a file
tao_bockstein.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mot_mult.dir/build.make CMakeFiles/mot_mult.dir/tao_bockstein.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yoneda.dir/build.make CMakeFiles/yoneda.dir/tao_bockstein.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tauBoc.dir/build.make CMakeFiles/tauBoc.dir/tao_bockstein.cpp.s
.PHONY : tao_bockstein.cpp.s

taubocmain.o: taubocmain.cpp.o
.PHONY : taubocmain.o

# target to build an object file
taubocmain.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tauBoc.dir/build.make CMakeFiles/tauBoc.dir/taubocmain.cpp.o
.PHONY : taubocmain.cpp.o

taubocmain.i: taubocmain.cpp.i
.PHONY : taubocmain.i

# target to preprocess a source file
taubocmain.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tauBoc.dir/build.make CMakeFiles/tauBoc.dir/taubocmain.cpp.i
.PHONY : taubocmain.cpp.i

taubocmain.s: taubocmain.cpp.s
.PHONY : taubocmain.s

# target to generate assembly for a file
taubocmain.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tauBoc.dir/build.make CMakeFiles/tauBoc.dir/taubocmain.cpp.s
.PHONY : taubocmain.cpp.s

yoneda.o: yoneda.cpp.o
.PHONY : yoneda.o

# target to build an object file
yoneda.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yoneda.dir/build.make CMakeFiles/yoneda.dir/yoneda.cpp.o
.PHONY : yoneda.cpp.o

yoneda.i: yoneda.cpp.i
.PHONY : yoneda.i

# target to preprocess a source file
yoneda.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yoneda.dir/build.make CMakeFiles/yoneda.dir/yoneda.cpp.i
.PHONY : yoneda.cpp.i

yoneda.s: yoneda.cpp.s
.PHONY : yoneda.s

# target to generate assembly for a file
yoneda.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yoneda.dir/build.make CMakeFiles/yoneda.dir/yoneda.cpp.s
.PHONY : yoneda.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... BPtab"
	@echo "... e2p"
	@echo "... kos"
	@echo "... motTab"
	@echo "... mot_comb"
	@echo "... mot_mult"
	@echo "... mr_BP"
	@echo "... mr_ex"
	@echo "... mr_mot"
	@echo "... mr_st"
	@echo "... tauBoc"
	@echo "... yoneda"
	@echo "... BP.o"
	@echo "... BP.i"
	@echo "... BP.s"
	@echo "... BPQ.o"
	@echo "... BPQ.i"
	@echo "... BPQ.s"
	@echo "... BP_init.o"
	@echo "... BP_init.i"
	@echo "... BP_init.s"
	@echo "... BPcomplex.o"
	@echo "... BPcomplex.i"
	@echo "... BPcomplex.s"
	@echo "... BPmain.o"
	@echo "... BPmain.i"
	@echo "... BPmain.s"
	@echo "... BPtable.o"
	@echo "... BPtable.i"
	@echo "... BPtable.s"
	@echo "... Boc.o"
	@echo "... Boc.i"
	@echo "... Boc.s"
	@echo "... Fp.o"
	@echo "... Fp.i"
	@echo "... Fp.s"
	@echo "... Qp.o"
	@echo "... Qp.i"
	@echo "... Qp.s"
	@echo "... Z2.o"
	@echo "... Z2.i"
	@echo "... Z2.s"
	@echo "... algNov.o"
	@echo "... algNov.i"
	@echo "... algNov.s"
	@echo "... ctau_steenrod.o"
	@echo "... ctau_steenrod.i"
	@echo "... ctau_steenrod.s"
	@echo "... ex2poly.o"
	@echo "... ex2poly.i"
	@echo "... ex2poly.s"
	@echo "... ex_exponents.o"
	@echo "... ex_exponents.i"
	@echo "... ex_exponents.s"
	@echo "... ex_index.o"
	@echo "... ex_index.i"
	@echo "... ex_index.s"
	@echo "... ex_main.o"
	@echo "... ex_main.i"
	@echo "... ex_main.s"
	@echo "... ex_steenrod_init.o"
	@echo "... ex_steenrod_init.i"
	@echo "... ex_steenrod_init.s"
	@echo "... exponents.o"
	@echo "... exponents.i"
	@echo "... exponents.s"
	@echo "... kosul.o"
	@echo "... kosul.i"
	@echo "... kosul.s"
	@echo "... mon_index.o"
	@echo "... mon_index.i"
	@echo "... mon_index.s"
	@echo "... mot_coactions.o"
	@echo "... mot_coactions.i"
	@echo "... mot_coactions.s"
	@echo "... mot_combine.o"
	@echo "... mot_combine.i"
	@echo "... mot_combine.s"
	@echo "... mot_main.o"
	@echo "... mot_main.i"
	@echo "... mot_main.s"
	@echo "... mot_mult.o"
	@echo "... mot_mult.i"
	@echo "... mot_mult.s"
	@echo "... mot_steenrod.o"
	@echo "... mot_steenrod.i"
	@echo "... mot_steenrod.s"
	@echo "... multiplication.o"
	@echo "... multiplication.i"
	@echo "... multiplication.s"
	@echo "... steenrod.o"
	@echo "... steenrod.i"
	@echo "... steenrod.s"
	@echo "... steenrod_init.o"
	@echo "... steenrod_init.i"
	@echo "... steenrod_init.s"
	@echo "... stmain.o"
	@echo "... stmain.i"
	@echo "... stmain.s"
	@echo "... streams.o"
	@echo "... streams.i"
	@echo "... streams.s"
	@echo "... tao_bockstein.o"
	@echo "... tao_bockstein.i"
	@echo "... tao_bockstein.s"
	@echo "... taubocmain.o"
	@echo "... taubocmain.i"
	@echo "... taubocmain.s"
	@echo "... yoneda.o"
	@echo "... yoneda.i"
	@echo "... yoneda.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

