const NS="http://www.w3.org/2000/svg", UNIT=42, MARGIN=30;
const SAMPLE=`[0-0]\t|deg=(0,0)\nv0^1[0-0]\t|deg=(0,1)\n[1-0]\t|deg=(3,1)`;
const state={nodes:[],diffs:[],products:{},enabledProducts:new Set(),productLines:[],scale:1,tx:MARGIN,ty:0,drag:null,selected:null,page:2,name:"sample",kind:"aanss"};
const $=id=>document.getElementById(id), svg=$("chart"), camera=$("camera");
const make=(tag,a={})=>{const n=document.createElementNS(NS,tag);for(const[k,v]of Object.entries(a))n.setAttribute(k,v);return n};
const DEFAULT_CELL_LABELS={m3:{bottom:"bottom-cell image (boundary zero)",top:"top-cell class (nonzero boundary)"},ahss:{bottom:"bottom cell",top:"top cell"},"two-cell":{bottom:"bottom-cell role",top:"top-cell role"}};
const isCellFiltered=kind=>kind==="m3"||kind==="two-cell"||kind==="ahss";
function setCellLegend(kind,cellLabels,hasCells=false){const defaults=DEFAULT_CELL_LABELS[kind]||DEFAULT_CELL_LABELS["two-cell"],labels=cellLabels&&typeof cellLabels==="object"?cellLabels:{};const value=key=>typeof labels[key]==="string"&&labels[key].trim()?labels[key]:defaults[key];$("bottomCellLabel").textContent=value("bottom");$("topCellLabel").textContent=value("top");$("cellLegend").classList.toggle("open",hasCells||isCellFiltered(kind))}
function key(name,x,y){return `${name}|${x}|${y}`}
function bracketFiltration(name){const m=name.match(/\[(-?\d+)-/);return m?Number(m[1]):null}
function parseTable(text,kind="aanss"){
  const nodes=[],diffs=[],byKey=new Map(); let id=0,maxPage=kind==="bockstein"?0:2;
  const add=(name,x,y,role="class",raw="")=>{const k=key(name,x,y),cell=(raw.match(/\|cell=(top|bottom)/)||[])[1]||null;if(byKey.has(k)){const n=byKey.get(k);if(role!=="class")n.role=role;if(cell)n.cell=cell;return n}const gen=(name.match(/\[([^\]]+)\]/)||[])[1]||"—",coeff=name.replace(/\[[^\]]+\].*/,"")||"1";const n={id:id++,name,x,y,gen,coeff,role,cell,raw,death:null};nodes.push(n);byKey.set(k,n);return n};
  for(const raw0 of text.split(/\r?\n/)){const raw=raw0.trim();if(!raw)continue;const pair=raw.match(/\|deg=\(([-\d]+),([-\d]+)\)/),single=raw.match(/\|deg=([-\d]+)/),parts=raw.split(/\s*<-\s*/),left=parts[0].split("|deg=")[0].trim(),right=parts[1]?parts[1].split("|")[0].trim():null,dmatch=raw.match(/\|d(\d+)/);
    if(kind==="bockstein"){
      if(!single)continue;const printed=Number(single[1]);
      if(right!==null&&dmatch){const r=Number(dmatch[1]),targetFiltration=bracketFiltration(left),sourceFiltration=bracketFiltration(right);if(targetFiltration===null||sourceFiltration===null||targetFiltration!==sourceFiltration+1)continue;const targetStem=(printed-targetFiltration)/2;if(!Number.isInteger(targetStem))continue;maxPage=Math.max(maxPage,r);const target=add(left,targetStem,targetFiltration,"target",raw),source=add(right,targetStem+1,sourceFiltration,"source",raw);target.death=r;source.death=r;diffs.push({source,target,r,raw})}
      else{const filtration=bracketFiltration(left),stem=filtration===null?NaN:(printed-filtration)/2;if(Number.isInteger(stem))add(left,stem,filtration,"class",raw)}
      continue;
    }
    if(!pair)continue;const x=Number(pair[1]),y=Number(pair[2]);
    if(right!==null&&dmatch){const r=Number(dmatch[1]);maxPage=Math.max(maxPage,r);const target=add(left,x,y,"target",raw),source=add(right,x+1,y-r,"source",raw);target.death=r;source.death=r;diffs.push({source,target,r,raw})}else add(left,x,y,"class",raw);
  }
  return {nodes,diffs,maxPage,defaultPage:kind==="bockstein"||kind==="ahss"?1:2};
}
function inferredProductFamily(label){const normalized=label.toLowerCase().replaceAll("_"," ");if(/(^|\s)a0(?:\s|$)/.test(normalized))return "a0";if(/(^|\s)a1(?:\s|$)/.test(normalized)||normalized.replaceAll(" ","").includes("alpha1")||/(^|\s)h0(?:\s|$)/.test(normalized))return "alpha1";const theta=normalized.match(/theta\s*(\d+)?/);if(theta)return `theta${theta[1]||""}`;return normalized.replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")||"product"}
function defaultProductVisible(label,family){const value=family||inferredProductFamily(label);return value==="a0"||value==="alpha1"||value.startsWith("theta")}
function parseProductText(text){const lines=[];if(typeof text!=="string")return lines;for(const raw0 of text.split(/\r?\n/)){const parts=raw0.split(/\s*->\s*/);if(parts.length<2)continue;const source=parts[0].trim(),counts=new Map();for(const name of parts[1].split("+").map(x=>x.trim()).filter(x=>x&&x!=="o"))counts.set(name,((counts.get(name)||0)+1)%3);const targets=[...counts].filter(([,coefficient])=>coefficient).map(([name,coefficient])=>({name,coefficient}));if(targets.length)lines.push({source,targets,raw:raw0.trim()})}return lines}
function parseProducts(products,kind="aanss"){
  const result={};let colorIndex=0;
  for(const [label,value] of Object.entries(products||{})){
    const legacy=typeof value==="string",family=legacy?inferredProductFamily(label):(value.family||inferredProductFamily(label)),pageData=legacy?(kind==="aanss"?{infinity:value}:{all:value}):(value.pages||value.pageRelations||{}),pages={};
    for(const [page,text] of Object.entries(pageData))pages[String(page).toLowerCase()]=parseProductText(typeof text==="string"?text:text&&text.text);
    result[label]={label,family,pages,colorIndex:colorIndex++,defaultVisible:legacy?defaultProductVisible(label,family):(typeof value.defaultVisible==="boolean"?value.defaultVisible:defaultProductVisible(label,family)),provenance:legacy?{}:(value.provenance||{})};
  }
  return result;
}
function relationsForPage(product,page=state.page){const pages=product.pages;if(page===Infinity)return pages.infinity||pages.inf||pages.all||[];const exact=pages[String(page)];if(exact)return exact;const earlier=Object.keys(pages).filter(key=>/^\d+$/.test(key)&&Number(key)<=page).sort((a,b)=>Number(b)-Number(a))[0];return (earlier&&pages[earlier])||pages.finite||pages.all||[]}
function findNode(name){return state.nodes.find(n=>n.name===name&&pageVisible(n))||state.nodes.find(n=>n.name===name)}
function offsets(){const groups=new Map();for(const n of state.nodes){const k=`${n.x},${n.y}`;(groups.get(k)||groups.set(k,[]).get(k)).push(n)}for(const group of groups.values())group.forEach((n,i)=>{n.ox=(i-(group.length-1)/2)*10;n.oy=0})}
const sx=n=>n.x*UNIT+n.ox, sy=n=>-n.y*UNIT+n.oy;
function pageVisible(n){return state.page===Infinity?n.death===null:n.death===null||state.page<=n.death}
function lineVisible(d){if(state.page===Infinity||state.page>d.r)return false;const mode=$("lineMode").value;return mode==="all"||(mode==="current"&&state.page===d.r)}
function renderGrid(){const g=$("grid");g.innerHTML="";const xmax=Math.max(12,...state.nodes.map(n=>n.x))+3,ymax=Math.max(8,...state.nodes.map(n=>n.y))+3,ymin=Math.min(0,...state.nodes.map(n=>n.y))-2;for(let x=0;x<=xmax;x++)g.append(make("line",{x1:x*UNIT,y1:-ymax*UNIT,x2:x*UNIT,y2:-ymin*UNIT,class:"grid-line"}));for(let y=ymin;y<=ymax;y++)g.append(make("line",{x1:0,y1:-y*UNIT,x2:xmax*UNIT,y2:-y*UNIT,class:"grid-line"}))}
function renderAxes(){const g=$("fixedAxes");g.innerHTML="";const w=svg.clientWidth,h=svg.clientHeight,originY=state.ty;g.append(make("rect",{x:0,y:0,width:MARGIN,height:h,fill:"white"}),make("rect",{x:0,y:h-MARGIN,width:w,height:MARGIN,fill:"white"}),make("line",{x1:MARGIN,y1:originY,x2:w,y2:originY,class:"axis"}),make("line",{x1:MARGIN,y1:0,x2:MARGIN,y2:h-MARGIN,class:"axis"}));const xmin=Math.max(0,Math.floor((-state.tx)/(UNIT*state.scale))),xmax=Math.ceil((w-state.tx)/(UNIT*state.scale));for(let x=xmin;x<=xmax;x++){const px=state.tx+x*UNIT*state.scale;if(px<MARGIN)continue;const t=make("text",{x:px,y:h-9,class:"tick"});t.textContent=x;g.append(t)}const ymin=Math.floor((state.ty-(h-MARGIN))/(UNIT*state.scale)),ymax=Math.ceil(state.ty/(UNIT*state.scale));for(let y=ymin;y<=ymax;y++){const py=state.ty-y*UNIT*state.scale;if(py>h-MARGIN||py<0)continue;const t=make("text",{x:MARGIN-6,y:py,class:"tick tick-y"});t.textContent=y;g.append(t)}const xt=make("text",{x:w-34,y:h-9,class:"axis-title"});xt.textContent="stem";g.append(xt);const yt=make("text",{x:6,y:14,class:"axis-title"});yt.textContent=state.kind==="aanss"||state.kind==="ahss"?"AANSS filtration":"ANSS filtration";g.append(yt)}
function render(){offsets();renderGrid();const pg=$("products"),dg=$("differentials"),bg=$("bullets"),sg=$("selection");pg.innerHTML=dg.innerHTML=bg.innerHTML=sg.innerHTML="";state.productLines=[];for(const [product,spec] of Object.entries(state.products)){if(!state.enabledProducts.has(product))continue;const relations=relationsForPage(spec);for(const relation of relations){const source=findNode(relation.source);if(!source||!pageVisible(source))continue;for(const targetTerm of relation.targets){const target=findNode(targetTerm.name);if(!target||!pageVisible(target))continue;const coefficientClass=` coeff-${targetTerm.coefficient}`,productClass=` product-${spec.colorIndex%12}`;pg.append(make("line",{x1:sx(source),y1:sy(source),x2:sx(target),y2:sy(target),class:`product-line${productClass}${coefficientClass}`}),make("circle",{cx:sx(target),cy:sy(target),r:10,class:`product-end${productClass}${coefficientClass}`}));state.productLines.push({source,target,label:product,coefficient:targetTerm.coefficient})}}}for(const d of state.diffs)if(lineVisible(d)){dg.append(make("line",{x1:sx(d.source),y1:sy(d.source),x2:sx(d.target),y2:sy(d.target),class:`differential d${Math.min(d.r,8)}`}))}for(const n of state.nodes)if(pageVisible(n)){if(state.selected===n.id)sg.append(make("rect",{x:n.x*UNIT-UNIT/2,y:-n.y*UNIT-UNIT/2,width:UNIT,height:UNIT,class:"cell"}));const cellClass=n.cell?` cell-${n.cell}`:"",c=make("circle",{cx:sx(n),cy:sy(n),r:6,class:`bullet ${n.role}${cellClass}${state.selected===n.id?" selected":""}`});c.onpointerenter=()=>{const ring=make("circle",{cx:sx(n),cy:sy(n),r:10,class:"hover-ring",id:"hoverRing"});bg.insertBefore(ring,c)};c.onpointerleave=()=>{const ring=$("hoverRing");if(ring)ring.remove()};c.onclick=e=>{e.stopPropagation();if(state.selected===n.id)showInfo(n,e.clientX,e.clientY);else{state.selected=n.id;$("info").classList.remove("open");render()}};bg.append(c)}applyTransform();renderAxes()}
function applyTransform(){camera.setAttribute("transform",`translate(${state.tx} ${state.ty}) scale(${state.scale})`)}
function showInfo(n,x,y){$("infoName").textContent=n.name;const cellRow=n.cell?`<tr><th>Cell</th><td>${n.cell}</td></tr>`:"";$("infoBody").innerHTML=`<table><tr><th>Degree</th><td>(${n.x}, ${n.y})</td></tr>${cellRow}<tr><th>Generator</th><td>${n.gen}</td></tr><tr><th>Coefficient</th><td>${n.coeff}</td></tr><tr><th>Status</th><td>${n.death!==null?`supports/receives d${n.death}`:"no differential recorded"}</td></tr></table><div class="raw"></div>`;$("infoBody").querySelector(".raw").textContent=n.raw;const box=$("info");box.style.left=`${Math.min(x+10,innerWidth-400)}px`;box.style.top=`${Math.min(y+10,innerHeight-190)}px`;box.classList.add("open")}
function pages(max,kind,defaultPage){const p=$("page");p.innerHTML="";if(isCellFiltered(kind)){const o=document.createElement("option");o.value=kind==="ahss"?"1":"2";o.textContent=kind==="ahss"?"cellular AHSS E1":"ANSS E2";p.append(o);p.value=o.value;return}const first=kind==="bockstein"?0:2,last=kind==="bockstein"?Math.max(first,max):Math.max(5,max);for(let r=first;r<=last;r++){const o=document.createElement("option");o.value=r;o.textContent=`E${r}`;p.append(o)}const o=document.createElement("option");o.value="inf";o.textContent="E∞";p.append(o);p.value=String(defaultPage)}
function productLegend(){const legend=$("productLegend");legend.innerHTML="";const visible=Object.entries(state.products).filter(([label,spec])=>state.enabledProducts.has(label)&&relationsForPage(spec).length);for(const [label,spec] of visible){const row=document.createElement("div"),swatch=document.createElement("span"),text=document.createElement("span");swatch.className=`product-swatch product-${spec.colorIndex%12}`;text.textContent=label;row.append(swatch,text);legend.append(row)}legend.classList.toggle("open",visible.length>0)}
function setProductSelection(mode){for(const [label,spec] of Object.entries(state.products)){if(mode==="none")state.enabledProducts.delete(label);else if(mode==="default"){if(spec.defaultVisible)state.enabledProducts.add(label);else state.enabledProducts.delete(label)}}updateProductControls();productLegend();render()}
function updateProductControls(){const menu=$("productMenu"),choices=$("productChoices"),entries=Object.entries(state.products);menu.hidden=!entries.length;choices.innerHTML="";let active=0;for(const [label,spec] of entries){const row=document.createElement("label"),checkbox=document.createElement("input"),swatch=document.createElement("span"),name=document.createElement("span"),count=document.createElement("small"),relations=relationsForPage(spec);checkbox.type="checkbox";checkbox.checked=state.enabledProducts.has(label);checkbox.disabled=!relations.length;checkbox.onchange=()=>{if(checkbox.checked)state.enabledProducts.add(label);else state.enabledProducts.delete(label);updateProductControls();productLegend();render()};swatch.className=`product-swatch product-${spec.colorIndex%12}`;name.textContent=label;count.textContent=relations.length?`${relations.length}`:"not on this page";row.className=relations.length?"product-choice":"product-choice unavailable";row.append(checkbox,swatch,name,count);choices.append(row);if(checkbox.checked&&relations.length)active++}$("productCount").textContent=entries.length?`${active}/${entries.length}`:"0"}
function reset(){state.scale=1;state.tx=MARGIN+10;state.ty=svg.clientHeight-MARGIN-10;render()}
function load(text,name,kind="aanss",productData={},cellLabels=null){const parsed=parseTable(text,kind);if(!parsed.nodes.length)return toast("No readable degree entries found");const products=parseProducts(productData,kind),enabledProducts=new Set(Object.entries(products).filter(([,spec])=>spec.defaultVisible).map(([label])=>label));Object.assign(state,{...parsed,products,enabledProducts,name,kind,selected:null,page:parsed.defaultPage});pages(parsed.maxPage,kind,parsed.defaultPage);updateProductControls();productLegend();setCellLegend(kind,cellLabels,parsed.nodes.some(n=>n.cell));document.title=`${name} · MinimalResolution`;reset();toast(`${name}: ${parsed.nodes.length} classes, ${parsed.diffs.length} differentials, ${Object.keys(products).length} multiplication types`)}
function zoom(rate,x,y){const old=state.scale,next=Math.max(.3,Math.min(8,old*rate));state.tx=x-(x-state.tx)*next/old;state.ty=y-(y-state.ty)*next/old;state.scale=next;render()}
function toast(s){const t=$("toast");t.textContent=s;t.classList.add("show");clearTimeout(t.timer);t.timer=setTimeout(()=>t.classList.remove("show"),2200)}
svg.onwheel=e=>{e.preventDefault();zoom(e.deltaY<0?1.12:.89,e.clientX,e.clientY)};svg.onpointerdown=e=>{if(e.target.classList.contains("bullet"))return;state.drag={x:e.clientX,y:e.clientY,tx:state.tx,ty:state.ty};svg.setPointerCapture(e.pointerId);svg.classList.add("dragging")};svg.onpointermove=e=>{if(!state.drag)return;state.tx=state.drag.tx+e.clientX-state.drag.x;state.ty=state.drag.ty+e.clientY-state.drag.y;applyTransform();renderAxes()};svg.onpointerup=()=>{state.drag=null;svg.classList.remove("dragging")};svg.onclick=()=>{state.selected=null;$("info").classList.remove("open");render()};
function inferredKind(name,fallback){if(/BPBocSS/i.test(name))return "bockstein";if(/C[_-]?(?:alpha|a)1.*AHSS/i.test(name))return "ahss";if(/M3.*ANSS/i.test(name))return "m3";if(/C[_-]?(?:alpha|a)1.*ANSS/i.test(name))return "two-cell";if(/BPAANSS/i.test(name))return "aanss";return fallback}
$("page").onchange=e=>{state.page=e.target.value==="inf"?Infinity:Number(e.target.value);updateProductControls();productLegend();render()};$("lineMode").onchange=render;$("productDefaults").onclick=()=>setProductSelection("default");$("productNone").onclick=()=>setProductSelection("none");$("closeInfo").onclick=()=>$("info").classList.remove("open");$("more").onclick=e=>{const selected=[...state.enabledProducts];const n={name:state.name,x:"—",y:"—",gen:`${state.nodes.length} classes`,coeff:`${state.diffs.length} differentials`,raw:`Displayed products: ${selected.join(", ")||"none"}\nAvailable products: ${Object.keys(state.products).join(", ")||"none"}`};showInfo(n,e.clientX-270,e.clientY+20)};$("fileInput").onchange=async e=>{const f=e.target.files[0];if(f)load(await f.text(),f.name,inferredKind(f.name,state.kind))};document.addEventListener("pointerdown",e=>{const menu=$("productMenu");if(menu.open&&!menu.contains(e.target))menu.removeAttribute("open")});window.onresize=render;
function fromQuery(){const requested=new URLSearchParams(location.search).get("data");if(!requested)return load(SAMPLE,"sample","aanss");if(!/^[A-Za-z0-9_.-]+$/.test(requested))return load(SAMPLE,"sample","aanss");const s=document.createElement("script");s.src=`data/${requested}.js`;s.onload=()=>{const d=globalThis.MINIMALRES_DATA;d&&load(d.text,d.name||requested,d.kind,d.products,d.cellLabels)};s.onerror=()=>{load(SAMPLE,"sample","aanss");toast(`Could not load data/${requested}.js`)};document.head.append(s)}
fromQuery();
