const NS="http://www.w3.org/2000/svg", UNIT=42, MARGIN=30;
const SAMPLE=`[0-0]\t|deg=(0,0)\nv0^1[0-0]\t|deg=(0,1)\n[1-0]\t|deg=(3,1)`;
const state={nodes:[],diffs:[],products:{},productLines:[],scale:1,tx:MARGIN,ty:0,drag:null,selected:null,page:2,name:"sample",kind:"aanss"};
const $=id=>document.getElementById(id), svg=$("chart"), camera=$("camera");
const make=(tag,a={})=>{const n=document.createElementNS(NS,tag);for(const[k,v]of Object.entries(a))n.setAttribute(k,v);return n};
function key(name,x,y){return `${name}|${x}|${y}`}
function bracketFiltration(name){const m=name.match(/\[(-?\d+)-/);return m?Number(m[1]):null}
function parseTable(text,kind="aanss"){
  const nodes=[],diffs=[],byKey=new Map(); let id=0,maxPage=kind==="bockstein"?0:2;
  const add=(name,x,y,role="class",raw="")=>{const k=key(name,x,y),cell=(raw.match(/\|cell=(top|bottom)/)||[])[1]||null;if(byKey.has(k)){const n=byKey.get(k);if(role!=="class")n.role=role;if(cell)n.cell=cell;return n}const gen=(name.match(/\[([^\]]+)\]/)||[])[1]||"—",coeff=name.replace(/\[[^\]]+\].*/,"")||"1";const n={id:id++,name,x,y,gen,coeff,role,cell,raw,death:null};nodes.push(n);byKey.set(k,n);return n};
  for(const raw0 of text.split(/\r?\n/)){const raw=raw0.trim();if(!raw)continue;const pair=raw.match(/\|deg=\(([-\d]+),([-\d]+)\)/),single=raw.match(/\|deg=([-\d]+)/),parts=raw.split(/\s*<-\s*/),left=parts[0].split("|deg=")[0].trim(),right=parts[1]?parts[1].split("|")[0].trim():null,dmatch=raw.match(/\|d(\d+)/);
    if(kind==="bockstein"){
      if(!single)continue;const printed=Number(single[1]);
      if(right!==null&&dmatch){const r=Number(dmatch[1]),targetFiltration=bracketFiltration(left),sourceFiltration=bracketFiltration(right);if(targetFiltration===null||sourceFiltration===null||targetFiltration!==sourceFiltration+1)continue;const targetStem=(printed-targetFiltration)/2;if(!Number.isInteger(targetStem))continue;maxPage=Math.max(maxPage,r);const target=add(left,targetStem,targetFiltration,"target",raw),source=add(right,targetStem+1,sourceFiltration,"source",raw);target.death=r;source.death=r;diffs.push({source,target,r,raw})}
      else{const filtration=bracketFiltration(left),stem=filtration===null?NaN:(printed-filtration)/2;if(Number.isInteger(stem))add(left,stem,filtration,"class",raw)}
      continue;
    }
    if(!pair)continue;const x=Number(pair[1]),y=Number(pair[2]);
    if(right!==null&&dmatch){const r=Number(dmatch[1]);maxPage=Math.max(maxPage,r);const target=add(left,x,y,"target",raw),source=add(right,x+1,y-r,"source",raw);target.death=r;source.death=r;diffs.push({source,target,r,raw})}else add(left,x,y,"class",raw);
  }
  return {nodes,diffs,maxPage,defaultPage:kind==="bockstein"?1:2};
}
function parseProducts(products){
  const result={};
  for(const [label,text] of Object.entries(products||{})){const lines=[];for(const raw0 of text.split(/\r?\n/)){const parts=raw0.split(/\s*->\s*/);if(parts.length<2)continue;const source=parts[0].trim(),counts=new Map();for(const name of parts[1].split("+").map(x=>x.trim()).filter(x=>x&&x!=="o"))counts.set(name,((counts.get(name)||0)+1)%3);const targets=[...counts].filter(([,coefficient])=>coefficient).map(([name,coefficient])=>({name,coefficient}));if(targets.length)lines.push({source,targets,raw:raw0.trim()})}result[label]=lines}
  return result;
}
function findNode(name){return state.nodes.find(n=>n.name===name&&pageVisible(n))||state.nodes.find(n=>n.name===name)}
function offsets(){const groups=new Map();for(const n of state.nodes){const k=`${n.x},${n.y}`;(groups.get(k)||groups.set(k,[]).get(k)).push(n)}for(const group of groups.values())group.forEach((n,i)=>{n.ox=(i-(group.length-1)/2)*10;n.oy=0})}
const sx=n=>n.x*UNIT+n.ox, sy=n=>-n.y*UNIT+n.oy;
function pageVisible(n){return state.page===Infinity?n.death===null:n.death===null||state.page<=n.death}
function lineVisible(d){if(state.page===Infinity||state.page>d.r)return false;const mode=$("lineMode").value;return mode==="all"||(mode==="current"&&state.page===d.r)}
function renderGrid(){const g=$("grid");g.innerHTML="";const xmax=Math.max(12,...state.nodes.map(n=>n.x))+3,ymax=Math.max(8,...state.nodes.map(n=>n.y))+3,ymin=Math.min(0,...state.nodes.map(n=>n.y))-2;for(let x=0;x<=xmax;x++)g.append(make("line",{x1:x*UNIT,y1:-ymax*UNIT,x2:x*UNIT,y2:-ymin*UNIT,class:"grid-line"}));for(let y=ymin;y<=ymax;y++)g.append(make("line",{x1:0,y1:-y*UNIT,x2:xmax*UNIT,y2:-y*UNIT,class:"grid-line"}))}
function renderAxes(){const g=$("fixedAxes");g.innerHTML="";const w=svg.clientWidth,h=svg.clientHeight,originY=state.ty;g.append(make("rect",{x:0,y:0,width:MARGIN,height:h,fill:"white"}),make("rect",{x:0,y:h-MARGIN,width:w,height:MARGIN,fill:"white"}),make("line",{x1:MARGIN,y1:originY,x2:w,y2:originY,class:"axis"}),make("line",{x1:MARGIN,y1:0,x2:MARGIN,y2:h-MARGIN,class:"axis"}));const xmin=Math.max(0,Math.floor((-state.tx)/(UNIT*state.scale))),xmax=Math.ceil((w-state.tx)/(UNIT*state.scale));for(let x=xmin;x<=xmax;x++){const px=state.tx+x*UNIT*state.scale;if(px<MARGIN)continue;const t=make("text",{x:px,y:h-9,class:"tick"});t.textContent=x;g.append(t)}const ymin=Math.floor((state.ty-(h-MARGIN))/(UNIT*state.scale)),ymax=Math.ceil(state.ty/(UNIT*state.scale));for(let y=ymin;y<=ymax;y++){const py=state.ty-y*UNIT*state.scale;if(py>h-MARGIN||py<0)continue;const t=make("text",{x:MARGIN-6,y:py,class:"tick tick-y"});t.textContent=y;g.append(t)}const xt=make("text",{x:w-34,y:h-9,class:"axis-title"});xt.textContent="stem";g.append(xt);const yt=make("text",{x:6,y:14,class:"axis-title"});yt.textContent=state.kind==="aanss"?"total Adams filtration":"ANSS filtration";g.append(yt)}
function render(){offsets();renderGrid();const pg=$("products"),dg=$("differentials"),bg=$("bullets"),sg=$("selection");pg.innerHTML=dg.innerHTML=bg.innerHTML=sg.innerHTML="";state.productLines=[];const product=$("productMode").value;if(product!=="none")for(const relation of state.products[product]||[]){const source=findNode(relation.source);if(!source||!pageVisible(source))continue;for(const targetTerm of relation.targets){const target=findNode(targetTerm.name);if(!target||!pageVisible(target))continue;const coefficientClass=` coeff-${targetTerm.coefficient}`;pg.append(make("line",{x1:sx(source),y1:sy(source),x2:sx(target),y2:sy(target),class:`product-line${coefficientClass}`}),make("circle",{cx:sx(target),cy:sy(target),r:10,class:`product-end${coefficientClass}`}));state.productLines.push({source,target,label:product,coefficient:targetTerm.coefficient})}}for(const d of state.diffs)if(lineVisible(d)){dg.append(make("line",{x1:sx(d.source),y1:sy(d.source),x2:sx(d.target),y2:sy(d.target),class:`differential d${Math.min(d.r,8)}`}))}for(const n of state.nodes)if(pageVisible(n)){if(state.selected===n.id)sg.append(make("rect",{x:n.x*UNIT-UNIT/2,y:-n.y*UNIT-UNIT/2,width:UNIT,height:UNIT,class:"cell"}));const cellClass=n.cell?` cell-${n.cell}`:"",c=make("circle",{cx:sx(n),cy:sy(n),r:6,class:`bullet ${n.role}${cellClass}${state.selected===n.id?" selected":""}`});c.onpointerenter=()=>{const ring=make("circle",{cx:sx(n),cy:sy(n),r:10,class:"hover-ring",id:"hoverRing"});bg.insertBefore(ring,c)};c.onpointerleave=()=>{const ring=$("hoverRing");if(ring)ring.remove()};c.onclick=e=>{e.stopPropagation();if(state.selected===n.id)showInfo(n,e.clientX,e.clientY);else{state.selected=n.id;$("info").classList.remove("open");render()}};bg.append(c)}applyTransform();renderAxes()}
function applyTransform(){camera.setAttribute("transform",`translate(${state.tx} ${state.ty}) scale(${state.scale})`)}
function showInfo(n,x,y){$("infoName").textContent=n.name;const cellRow=n.cell?`<tr><th>Cell</th><td>${n.cell}</td></tr>`:"";$("infoBody").innerHTML=`<table><tr><th>Degree</th><td>(${n.x}, ${n.y})</td></tr>${cellRow}<tr><th>Generator</th><td>${n.gen}</td></tr><tr><th>Coefficient</th><td>${n.coeff}</td></tr><tr><th>Status</th><td>${n.death!==null?`supports/receives d${n.death}`:"no differential recorded"}</td></tr></table><div class="raw"></div>`;$("infoBody").querySelector(".raw").textContent=n.raw;const box=$("info");box.style.left=`${Math.min(x+10,innerWidth-400)}px`;box.style.top=`${Math.min(y+10,innerHeight-190)}px`;box.classList.add("open")}
function pages(max,kind,defaultPage){const p=$("page");p.innerHTML="";if(kind==="m3"){const o=document.createElement("option");o.value="2";o.textContent="ANSS E2";p.append(o);p.value="2";return}const first=kind==="bockstein"?0:2,last=kind==="bockstein"?Math.max(first,max):Math.max(5,max);for(let r=first;r<=last;r++){const o=document.createElement("option");o.value=r;o.textContent=`E${r}`;p.append(o)}const o=document.createElement("option");o.value="inf";o.textContent="E∞";p.append(o);p.value=String(defaultPage)}
function productMenu(products){const p=$("productMode");p.innerHTML='<option value="none">No products</option>';for(const label of Object.keys(products)){const o=document.createElement("option");o.value=label;o.textContent=label;p.append(o)}p.value=Object.keys(products).includes("h0")?"h0":"none"}
function reset(){state.scale=1;state.tx=MARGIN+10;state.ty=svg.clientHeight-MARGIN-10;render()}
function load(text,name,kind="aanss",productData={}){const parsed=parseTable(text,kind);if(!parsed.nodes.length)return toast("No readable degree entries found");const products=parseProducts(productData);Object.assign(state,{...parsed,products,name,kind,selected:null,page:parsed.defaultPage});pages(parsed.maxPage,kind,parsed.defaultPage);productMenu(products);$("cellLegend").classList.toggle("open",kind==="m3");document.title=`${name} · MinimalResolution`;reset();toast(`${name}: ${parsed.nodes.length} classes, ${parsed.diffs.length} differentials, ${Object.keys(products).length} products`)}
function zoom(rate,x,y){const old=state.scale,next=Math.max(.3,Math.min(8,old*rate));state.tx=x-(x-state.tx)*next/old;state.ty=y-(y-state.ty)*next/old;state.scale=next;render()}
function toast(s){const t=$("toast");t.textContent=s;t.classList.add("show");clearTimeout(t.timer);t.timer=setTimeout(()=>t.classList.remove("show"),2200)}
svg.onwheel=e=>{e.preventDefault();zoom(e.deltaY<0?1.12:.89,e.clientX,e.clientY)};svg.onpointerdown=e=>{if(e.target.classList.contains("bullet"))return;state.drag={x:e.clientX,y:e.clientY,tx:state.tx,ty:state.ty};svg.setPointerCapture(e.pointerId);svg.classList.add("dragging")};svg.onpointermove=e=>{if(!state.drag)return;state.tx=state.drag.tx+e.clientX-state.drag.x;state.ty=state.drag.ty+e.clientY-state.drag.y;applyTransform();renderAxes()};svg.onpointerup=()=>{state.drag=null;svg.classList.remove("dragging")};svg.onclick=()=>{state.selected=null;$("info").classList.remove("open");render()};
function inferredKind(name,fallback){if(/BPBocSS/i.test(name))return "bockstein";if(/M3.*ANSS/i.test(name))return "m3";if(/BPAANSS/i.test(name))return "aanss";return fallback}
$("page").onchange=e=>{state.page=e.target.value==="inf"?Infinity:Number(e.target.value);render()};$("lineMode").onchange=render;$("productMode").onchange=render;$("closeInfo").onclick=()=>$("info").classList.remove("open");$("more").onclick=e=>{const n={name:state.name,x:"—",y:"—",gen:`${state.nodes.length} classes`,coeff:`${state.diffs.length} differentials`,raw:`Products: ${Object.keys(state.products).join(", ")||"none"}`};showInfo(n,e.clientX-270,e.clientY+20)};$("fileInput").onchange=async e=>{const f=e.target.files[0];if(f)load(await f.text(),f.name,inferredKind(f.name,state.kind))};window.onresize=render;
function fromQuery(){const requested=new URLSearchParams(location.search).get("data");if(!requested)return load(SAMPLE,"sample","aanss");if(!/^[A-Za-z0-9_.-]+$/.test(requested))return load(SAMPLE,"sample","aanss");const s=document.createElement("script");s.src=`data/${requested}.js`;s.onload=()=>{const d=globalThis.MINIMALRES_DATA;d&&load(d.text,d.name||requested,d.kind,d.products)};s.onerror=()=>{load(SAMPLE,"sample","aanss");toast(`Could not load data/${requested}.js`)};document.head.append(s)}
fromQuery();
